[package]
name = "nexmon-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
csi = { path = "../csi" }

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"

[dependencies]
num-complex = "0.4.4"
