[package]
name = "nexmon-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
csi = { path = "../csi" }

[dependencies]
makecsiparams-sys = { path = "../makecsiparams-sys" }
nexmon-test-sys = { path = "nexmon-test-sys" }
num-complex = "0.4.4"
