[package]
name = "csi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
base64 = "0.21"
bitflags = "2.4"
macaddr = "1.0"
num-complex = "0.4"
num-traits = "0.2.17"
thiserror = "1.0.50"
