[package]
name = "sensor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-ssh2-tokio = { version = "0.8.4", features = ["openssl"] }
csi = { path = "../csi" }
macaddr = "1.0.1"
pcap-file-tokio = "0.1.0"
russh = "0.40.0"
tokio = { version = "1.35.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
